### PR TITLE
feat: added the sum of latency query in ui

### LINKED ISSUE #25: feature: show the latency of the query in the UI
On the search route, we return the latency of the query for each component in the timing headers and we should display the sum of these: 

image

The end result should look similar to what Algolia does:

image

### PR DESCRIPTION
**Pull request by Gmin2**
fixes #25 
/claim #25 

image

### CODE REVIEW

**Comment by skeptrunedev** [comment]
Can you include a screenshot showing how this displays please?

**Comment by Gmin2** [comment]
> Can you include a screenshot showing how this displays please?

Done @skeptrunedev

**Review by skeptrunedev — CHANGES_REQUESTED** [review]
This should be above the search bar on the right as it was in the image on the issue. Also, it should not have a different font color.

**Comment by Gmin2** [comment]
> This should be above the search bar on the right as it was in the image on the issue. Also, it should not have a different font color.

Push the changes mentioned @skeptrunedev

**Review by skeptrunedev — CHANGES_REQUESTED** [review]
This still isn't correct. Should be in the unit of seconds and have no color modifier. Just let it be the default color of the parent.

See the example:

image

**Comment by Gmin2** [comment]
image

cc @skeptrunedev

**Comment by skeptrunedev** [comment]
Well it was close, but needed a lint and I cleaned up the code a bit. Will still award the bounty.

**Review by skeptrunedev — APPROVED** [review]

**Comment by Gmin2** [comment]
@skeptrunedev i think you have forget to approve the bounty for this

**Pull request merged**
